version: "3.8"

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_INTERNAL_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    image: task
    command: ["java","-jar","/app.jar"]
    build: .
    env_file: .env
    ports:
      - $SPRING_LOCAL_PORT:$SERVER_PORT
    environment:
      - server.port=6161
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/vibbrademo
      - spring.datasource.username=services
      - spring.datasource.password=123123

    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: