version: "3.8"

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'vibbra'
      MYSQL_PASSWORD: '123456'
      MYSQL_USER: 'user'
    ports:
      - 4445:3306
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    image: task
    command: ["java","-jar","/app.jar"]
    build: .
    restart: unless-stopped
    ports:
      - 6161:6161
    environment:
      - server.port=6161
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/vibbra?useSSL=false&allowPublicKeyRetrieval=true
      - spring.datasource.username=root
      - spring.datasource.password=123456

volumes:
  db: