version: "3.8"

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_INTERNAL_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    image: task
    command: ["java","-jar","/app.jar"]
    build: .
    env_file: .env
    ports:
      - $SPRING_LOCAL_PORT:$SERVER_PORT
    environment:
      - server.port=$SERVER_PORT
      - spring.datasource.url=jdbc:mysql://$MYSQL_HOST:$MYSQLDB_INTERNAL_DOCKER_PORT/$MYSQLDB_DATABASE
      - spring.datasource.username=$MYSQLDB_USER
      - spring.datasource.password=$MYSQLDB_ROOT_PASSWORD

volumes:
  db: